# https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html

- name: Install all components for every node
  ansible.builtin.import_playbook: ansible_dir/k8s_components_installer.playbook.yml

- name: Install containerd.io
  ansible.builtin.import_playbook: ansible_dir/k8s.containerd.playbook.yml

- name: Init cluster
  ansible.builtin.import_playbook: ansible_dir/k8s_cluster_initial.playbook.yml

- name: Masters join
  ansible.builtin.import_playbook: ansible_dir/k8s_join_masters.playbook.yml

- name: Kubectl configuration
  ansible.builtin.import_playbook: ansible_dir/k8s_config_kubectl.playbook.yml

- name: Install metrics-server by helm
  ansible.builtin.import_playbook: ansible_dir/k8s.metrics_server.playbook.yml

- name: Install Cilium network by helm
  ansible.builtin.import_playbook: ansible_dir/k8s.cilium_network.playbook.yml

- name: Workers join
  ansible.builtin.import_playbook: ansible_dir/k8s_join_workers.playbook.yml

- name: Install ingress-nginx by helm
  ansible.builtin.import_playbook: ansible_dir/k8s.ingress_nginx.playbook.yml

- name: Install crictl tool to query pods and containers
  ansible.builtin.import_playbook: ansible_dir/k8s_crictl_component.playbook.yml

- name: Loadbalancer for workers
  ansible.builtin.import_playbook: ansible_dir/k8s.worker_lb.playbook.yml

- name: Print some debug info
  ansible.builtin.import_playbook: ansible_dir/k8s_debug_print.playbook.yml
