- name: Get join command
  ansible.builtin.import_playbook: k8s_join_command.playbook.yml

- name: Other Control planes joining
  hosts: masters,!master_1
  tasks:
    - name: Check kubelet info for sure the current node is not in any cluster
      ansible.builtin.stat:
        path: "/etc/kubernetes/kubelet.conf"
      register: kubernetes_kubelet_conf

    - name: Check if port 6443 is listening
      ansible.builtin.wait_for:
        host: 0.0.0.0
        port: 6443
        timeout: 1
        msg: "Timeout waiting for port 6443 to respond"
      register: portcheck6443
      ignore_errors: true

    - name: Run command to join
      become: true
      ansible.builtin.command:
        cmd: >-
          {{ hostvars.master_1.kubernetes_worker_join_command.stdout_lines[0] }}
          --control-plane --certificate-key
          {{ hostvars.master_1.kubernetes_cerfiticate_key.stdout_lines[0] }}
        chdir: $HOME
      when:
        - not kubernetes_kubelet_conf.stat.exists
        - portcheck6443.failed
        - hostvars['master_1']['kubernetes_worker_join_command'] is defined
        - hostvars['master_1']['kubernetes_cerfiticate_key'] is defined
      register: kubernetes_control_plane_join
      failed_when: kubernetes_control_plane_join.rc != 0
      changed_when: kubernetes_control_plane_join.rc == 0

    - name: Get stat of /etc/kubernetes/admin.conf
      ansible.builtin.stat:
        path: "/etc/kubernetes/admin.conf"
      register: kubernetes_admin_conf

    - name: Mkdir .kube directory
      ansible.builtin.file:
        path: "$HOME/.kube"
        state: "directory"
        mode: "0755"

    - name: Copies admin.conf to user's kube config
      become: true
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: a+r
        remote_src: true
      when: kubernetes_admin_conf.stat.exists
