---
# tasks file for roles/prometheus

- name: Update and install prometheus
  ansible.builtin.apt:
    name: prometheus
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Prometheus args
  ansible.builtin.template:
    src: prometheus.j2
    dest: /etc/default/prometheus
    mode: 0644
    owner: root
    group: root
  notify: Restart_prometheus

- name: Prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_configuration }}/prometheus.yml"
    mode: 0755
    owner: prometheus
    group: prometheus
  notify: Reload_prometheus

- name: Start prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: started
    enabled: true
