---
# tasks file for roles/grafana

- name: Install gpg
  apt:
    name: gnupg,software-properties-common
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Add gpg hey
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: false

- name: Add repository
  apt_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: false

- name: Install grafana
  apt:
    name: grafana
    state: latest
    update_cache: true
    cache_valid_time: 3600

- name: Start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: true

- name: Wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

- name: Change admin password for grafana gui
  shell : "grafana-cli admin reset-admin-password {{ grafana_admin_password }}"
  register: __command_admin
  changed_when: __command_admin.rc !=0