- name: Install Worker loadbalancer
  hosts: worker_lbs
  tags:
    - addNode
    - deleteNode
  handlers:
    - name: Reload nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded

    - name: Restart rsyslog
      become: true
      ansible.builtin.service:
        name: rsyslog
        state: restarted

  tasks:
    - name: Install rsyslog
      become: true
      ansible.builtin.apt:
        name: rsyslog
        state: present
        update_cache: true

    - name: Upload worker_lb.nginx.rsyslog.conf
      become: true
      ansible.builtin.template:
        dest: "/etc/rsyslog.d/nginx.conf"
        src: worker_lb.nginx.rsyslog.conf
        mode: a+r
      notify:
        - Restart rsyslog

    - name: Start rsyslog
      become: true
      ansible.builtin.service:
        name: rsyslog
        state: started
        enabled: true

    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: Start nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Upload worker_lb.nginx.conf
      become: true
      ansible.builtin.template:
        dest: /etc/nginx/nginx.conf
        src: worker_lb.nginx.conf
        mode: a+r
      notify:
        - Reload nginx
