- name: Install cilium network to the cluster
  hosts: masters
  run_once: true
  tasks:
    # helm repo add cilium https://helm.cilium.io/
    - name: Add cilium chart repo
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"

    # https://docs.cilium.io/en/stable/network/kubernetes/kubeproxy-free/#kubeproxy-free
    # helm install cilium cilium/cilium --version 1.14.0 --namespace kube-system
    # https://docs.cilium.io/en/v1.14/helm-reference/
    - name: Deploy cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: 1.14.2
        release_namespace: kube-system
        create_namespace: true
        set_values:
          # Replace kube-proxy
          - value: kubeProxyReplacement=true
          # kubernetes API address
          # Do not use kubernetes API address by ClusterIP because kube-proxy is gone this time
          - value: k8sServiceHost={{ hostvars.master_lb_1.private_ip }}
          - value: k8sServicePort={{ control_plane_endpoint_port }}
          # Do so by providing new values to Helm and applying them to the existing installation.
          # The agent pods will be gradually restarted.
          - value: rollOutCiliumPods=true
          - value: ipv4.enabled=true
          - value: ipv6.enabled=true
          - value: ipam.mode=cluster-pool
          - value: ipam.operator.clusterPoolIPv4PodCIDRList={{ cilium_pod_network_cidr_v4 }}
          - value: ipam.operator.clusterPoolIPv6PodCIDRList={{ cilium_pod_network_cidr_v6 }}
          - value: ipam.operator.clusterPoolIPv4MaskSize=24
          - value: ipam.operator.clusterPoolIPv6MaskSize=112
          - value: hubble.relay.enabled=true
          - value: hubble.peerService.clusterDomain={{ cluster_domain }}
          - value: hubble.ui.enabled=true
          # * Other features
          # ** Uncomment and re-deploy to apply
          # ** We should manually restart
          # ** kubectl -n kube-system rollout restart deployment/cilium-operator
          # ** kubectl -n kube-system rollout restart ds/cilium
          # * Feature: Ingress controller support https://docs.cilium.io/en/stable/network/servicemesh/ingress/#gs-ingress
          # ** It currently does not support dualstack
          # - value: ingressController.enabled=true
          # - value: ingressController.loadbalancerMode=shared
          # * Feature: Egress gateway https://docs.cilium.io/en/stable/network/egress-gateway/
          # - value: egressGateway.enabled=true
          # - value: bpf.masquerade=true
          # * Feature: Enable support for Gateway API in cilium This will automatically set enable-envoy-config as well.
          # ** Refer: https://docs.cilium.io/en/stable/network/servicemesh/gateway-api/gateway-api/#cilium-gateway-api-support
          # ** It currently does not support dualstack
          # - value: gatewayAPI.enabled=true
