- name: Install open-iscsi
  hosts: masters,workers
  tags:
    - addNode
  tasks:
    # https://longhorn.io/docs/archives/0.8.0/install/requirements/
    - name: Install open-iscsi
      become: true
      ansible.builtin.apt:
        name: open-iscsi
        state: present
        update_cache: true

- name: Install longhorn storage by helm
  hosts: masters
  run_once: true
  tasks:
    # helm repo add longhorn https://charts.longhorn.io
    - name: Add longhorn chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    # https://artifacthub.io/packages/helm/longhorn/longhorn
    # helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
    - name: Deploy longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        chart_version: 1.5.1
        release_namespace: longhorn-system
        create_namespace: true
