- name: Get join command
  ansible.builtin.import_playbook: k8s_join_command.playbook.yml
  tags:
    - addNode

- name: Other Control planes joining
  hosts: masters,!master_1
  tags:
    - addNode
  tasks:
    - name: Check kubelet info for sure the current node is not in any cluster
      ansible.builtin.stat:
        path: "/etc/kubernetes/kubelet.conf"
      register: kubernetes_kubelet_conf

    - name: Check if apiserver port is listening
      ansible.builtin.wait_for:
        host: 0.0.0.0
        port: "{{ apiserver_bind_port }}"
        timeout: 1
        msg: "Timeout waiting for port 6443 to respond"
      register: apiserverportcheck
      ignore_errors: true

    - name: Run command to join
      become: true
      ansible.builtin.command:
        cmd: >-
          {{ hostvars.master_1.kubernetes_worker_join_command.stdout_lines[0] }}
          --control-plane --certificate-key
          {{ hostvars.master_1.kubernetes_cerfiticate_key.stdout_lines[0] }}
        chdir: $HOME
      when:
        - not kubernetes_kubelet_conf.stat.exists
        - apiserverportcheck.failed
        - hostvars['master_1']['kubernetes_worker_join_command'] is defined
        - hostvars['master_1']['kubernetes_cerfiticate_key'] is defined
      register: kubernetes_control_plane_join
      failed_when: kubernetes_control_plane_join.rc != 0
      changed_when: kubernetes_control_plane_join.rc == 0
