- name: Prepare some nesessary for longhorn
  hosts: masters,workers
  gather_facts: true
  tags:
    - addNode
  tasks:
    # https://longhorn.io/docs/1.5.1/deploy/install/#installation-requirements
    - name: Apt Install list of common packages
      become: true
      when: ansible_pkg_mgr == "apt"
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - curl
        - util-linux # findmnt
        - grep
        - gawk
        - fdisk # blkid, lsblk

    - name: Apt Install list of common packages
      become: true
      when: ansible_pkg_mgr == "yum"
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - grep
        - gawk
        - util-linux # findmnt, blkid, lsblk

    - name: Dnf Install list of common packages
      become: true
      when: ansible_pkg_mgr == "dnf"
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - grep
        - gawk
        - util-linux # findmnt, blkid, lsblk

    # https://longhorn.io/docs/1.5.1/deploy/install/#installing-open-iscsi
    - name: Add iscsi_tcp module to kernel
      become: true
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - iscsi_tcp

    - name: Add iscsi_tcp module to kernel (at boot time)
      become: true
      ansible.builtin.blockinfile:
        path: "/etc/modules-load.d/iscsi.conf"
        block: |
          iscsi_tcp
        create: true
        mode: u+r

    - name: Apt Install open-iscsi
      become: true
      when: ansible_pkg_mgr == "apt"
      ansible.builtin.apt:
        name: open-iscsi
        state: present
        update_cache: true

    - name: Yum Install iscsi-initiator-utils
      become: true
      when: ansible_pkg_mgr == "yum"
      ansible.builtin.yum:
        name: iscsi-initiator-utils
        state: present

    - name: Dnf Install iscsi-initiator-utils
      become: true
      when: ansible_pkg_mgr == "dnf"
      ansible.builtin.dnf:
        name: iscsi-initiator-utils
        state: present

    # https://longhorn.io/docs/1.5.1/advanced-resources/rwx-workloads/
    # https://longhorn.io/docs/1.5.1/deploy/install/#installing-nfsv4-client
    - name: Add nfs module to kernel
      become: true
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - nfs

    - name: Add nfs module to kernel (at boot time)
      become: true
      ansible.builtin.blockinfile:
        path: "/etc/modules-load.d/nfs.conf"
        block: |
          nfs
        create: true
        mode: u+r

    - name: Apt Install nfs-common
      become: true
      when: ansible_pkg_mgr == "apt"
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: true

    - name: Yum Install nfs-utils
      become: true
      when: ansible_pkg_mgr == "yum"
      ansible.builtin.yum:
        name: nfs-utils
        state: present

    - name: Dnf Install nfs-utils
      become: true
      when: ansible_pkg_mgr == "dnf"
      ansible.builtin.dnf:
        name: nfs-utils
        state: present
