- name: Install longhorn storage by helm
  hosts: masters
  run_once: true
  gather_facts: true
  tasks:
    # helm repo add longhorn https://charts.longhorn.io
    - name: Add longhorn chart repo
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    # https://raw.githubusercontent.com/longhorn/charts/master/charts/longhorn/values.yaml
    - name: Create value file for helm longhorn
      ansible.builtin.blockinfile:
        path: "{{ ansible_env.HOME }}/longhorn-values.yml"
        create: true
        mode: a+r
        block: |
          longhornUI:
            replicas: 1
          defaultSettings:
            # https://longhorn.io/docs/1.5.1/high-availability/k8s-cluster-autoscaler/
            kubernetesClusterAutoscalerEnabled: true
            # https://longhorn.io/docs/1.5.1/high-availability/auto-balance-replicas/#global-setting
            replicaAutoBalance: "least-effort"

    # https://artifacthub.io/packages/helm/longhorn/longhorn
    # helm upgrade --install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace
    - name: Deploy longhorn
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        chart_version: 1.5.1
        release_namespace: longhorn-system
        create_namespace: true
        values_files:
          - "{{ ansible_env.HOME }}/longhorn-values.yml"
